### PR TITLE
Compiling on RHEL9

### PR DESCRIPTION
**Pull request by Angelyr**
Small change for compiling on rhel9

### CODE REVIEW

**Comment by cwsmith** [comment]
What error are we hitting without this?  IIUC, if Cabana is built with HDF5 disabled we should be able to avoid this:
https://github.com/ECP-copa/Cabana/blob/80b0194b687024bcbd850f1491e345ac94baf64a/CMakeLists.txt#L72-L75

**Comment by Angelyr** [comment]
@cwsmith 
Yes that works if I also downgrade the cmake version because of this function:
https://github.com/ECP-copa/Cabana/blob/80b0194b687024bcbd850f1491e345ac94baf64a/CMakeLists.txt#L109-L119

**Comment by cwsmith** [comment]
@Angelyr Interesting.  It looks like we can still disable HDF5 in cabana with latest cmake:
https://github.com/ECP-copa/Cabana/blob/80b0194b687024bcbd850f1491e345ac94baf64a/CMakeLists.txt#L63
Setting `-DCabana_REQUIRE_HDF5=OFF` should work IIUC.

**Comment by Angelyr** [comment]
@cwsmith That still doesn't work because it still builds HDF5 with the C components because of this line:
https://github.com/ECP-copa/Cabana/blob/25f7411a1fc7c46ee2fc07ee0c452d8f589ff178/CMakeLists.txt#L60

**Review by cwsmith — APPROVED** [review]

**Comment by cwsmith** [comment]
@Angelyr Doh.  That's unfortunate.  I approved the changes.  Sorry for holding this up.

**Pull request merged**
