### PR TITLE
CabM particle structure

### PR DESCRIPTION
**Pull request by MatthewChristoff**
Cabana-based particle structure

Note that there are some small changes outside of the CabM structure. All of these are related to testing. Specifically, note that `SCS::rebuild` time is now being subtracted from `SCS::migrate` time in `scs_migrate.hpp`, [here](https://github.com/SCOREC/pumi-pic/pull/60/files#diff-f94174398aba63f4b26ac5b26f0b62556be3996b6ec33b22cf4bc292bb0731d3R202). The rest are almost entirely on unit/performance tests.

Things that still need to be done:
- [x] Destructor (Unneeded, no memory leaks)
- [x] printFormat (compare to SCS function)
- [x] printMetric extension to calculate amount of padding
- [x] builds with Cabana/CabM disabled  (@cwsmith will do this)

### CODE REVIEW

**Comment by diamog** [comment]
An additional test we should ensure works before merging to master is that pumi-pic can be built without Cabana available/enabled

**Comment by diamog** [comment]
@cwsmith I have some time that I can spend ensuring the build works without Cabana if you want me to pass it to me. I want to get these branches merged before I continue working on ParticleStructures V2.0

**Comment by cwsmith** [comment]
@diamog Thank you.  I'm working getting cmake to build without cabana now for `cabmBuild`.  When I get this set I will likely need help with some of the source.

**Comment by cwsmith** [comment]
@diamog I just pushed some commits that "start" adding support for compiling without cabm... The changes in https://github.com/SCOREC/pumi-pic/pull/60/commits/9a366a758bd95fa8761235b5e704809c73f4ee23 are most likely nonsense.  I gladly accept your offer to resolve the Cabana exists vs !exists issues :)

Please let me know if you have any problems getting cmake to run.

**Comment by diamog** [comment]
The above commit compiles and passes tests for builds with and without Cabana. I want to check that GITRm and XGCm build with this setup before merging. I should be able to do that tomorrow

**Comment by cwsmith** [comment]
The conflict is around the use of `SegmentInt` here:

https://github.com/SCOREC/pumi-pic/blob/c72b24398ba21b0fc70e11d538c153b7e21975b8/src/pumipic_adjacency.hpp#L433-L440

in master:

https://github.com/SCOREC/pumi-pic/blob/a732211ace536cb490435573cd513f25f61af036/src/pumipic_adjacency.hpp#L433-L441

`SegmentInt` is no longer a template arg, but is instead defined here:

https://github.com/SCOREC/pumi-pic/blob/a732211ace536cb490435573cd513f25f61af036/src/pumipic_kktypes.hpp#L21

I'll try to push changes here that resolve the merge conflicts (but will result in compile errors) and fix a compile error.  I'm trying to avoid merging master into this branch before merging back to master...

**Comment by cwsmith** [comment]
I gave in, merged master into cabmBuild, and pushed.  Adding a few merge commits to the history isn't too bad.

With this push the build without cabana succeeds, but the build with cabana fails with:

```
[ 70%] Building CXX object test/CMakeFiles/pseudoXGCm.dir/pseudoXGCm.cpp.o
cd /space/cwsmith/ppCabm/build-pumipicCabm-blockade-cuda/test && /opt/scorec/spack/install/linux-rhel7-x86_64/gcc-7.3.0/mpich-3.3-diz4f6ieln25ouifyc7ndtqlfksom6nb/bin/mpicxx  -DFP64 -DKOKKOS_ENABLED -DLOCAL_ID_FTYPE=C_INT32_T -DLOCAL_ID_TYPE=int32_t -DPP_ENABLE_CABM -DPP_USE_CUDA -I/space/cwsmith/ppCabm/pumi-pic-cabm/support -I/space/cwsmith/ppCabm/pumi-pic-cabm/support/support -I/space/cwsmith/ppCabm/build-cabana-blockade-cuda/install/include -I/space/cwsmith/ppCabm/pumi-pic-cabm/particle_structs/src -I/space/cwsmith/ppCabm/pumi-pic-cabm/particle_structs/src/support -I/space/cwsmith/ppCabm/pumi-pic-cabm/particle_structs/src/scs -I/space/cwsmith/ppCabm/pumi-pic-cabm/particle_structs/src/csr -I/space/cwsmith/ppCabm/pumi-pic-cabm/particle_structs/src/cabm -I/space/cwsmith/ppCabm/pumi-pic-cabm/src -isystem /space/cwsmith/ppCabm/build-kokkos-blockade-cuda/install/include -isystem /usr/local/cuda-10.2/include -isystem /space/cwsmith/ppCabm/build-omegah-blockade-cuda/install/include -isystem /space/cwsmith/ppCabm/build-engpar-blockade-cuda/install/include  --std=c++11 -lineinfo -g -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -expt-extended-lambda -arch=sm_75 -o CMakeFiles/pseudoXGCm.dir/pseudoXGCm.cpp.o -c /space/cwsmith/ppCabm/pumi-pic-cabm/test/pseudoXGCm.cpp
/space/cwsmith/ppCabm/pumi-pic-cabm/src/pumipic_adjacency.hpp(438): error: identifier "SegmentInt" is undefined
```

**Pull request merged**
