### PR TITLE
CSR migrate, and more

### PR DESCRIPTION
**Pull request by cwsmith**
This PR includes:
 - CSR migrate
 - CabM swap https://github.com/SCOREC/pumi-pic/commit/e7564062b6983015a8df732b4d0d6d0128937b8f
 - particle structure (PS) pre-barrier 5347564
 - PS testing
 - pseudo gitrm particle distribution b1f8663 
 - fixed performance problem with call to `atomic_fetch_add` 8df761e2fa701bb1b976ce968cf7e77adf3a0c35

### CODE REVIEW

**Comment by cwsmith** [comment]
The following two tests fail:

```
The following tests FAILED:
         20 - test_structures_small_4 (Failed)
         21 - test_structures_4 (Failed)
```

**Comment by MatthewChristoff** [comment]
> 
> 
> The following two tests fail with Cabana enabled and Cabana disabled:
> 
> ```
> The following tests FAILED:
>          20 - test_structures_small_4 (Failed)
>          21 - test_structures_4 (Failed)
> ```

These failures are happening during a "new" migration test. Technically, they were old tests that never had their function call uncommented. I renamed the test `migrateSendRight`, and it is now located [here](https://github.com/SCOREC/pumi-pic/blob/926188ae560b8554877a4287e7c1b5455aad8365/particle_structs/test/test_migrate.cpp#L4-L92) (I moved another commented-out migration test here along with another test we made more recently).

Specifically, `CSR` causes an `out-of-memory` error which happens during the second part of this test where a `Distributor` is used in the process of reversing a `migrate` operation with another `migrate` operation. This section is [here](https://github.com/SCOREC/pumi-pic/blob/926188ae560b8554877a4287e7c1b5455aad8365/particle_structs/test/test_migrate.cpp#L56-L90).

Error on `test_structures_small_4`:

```
20: testMigration csr, rank 2
20: terminate called after throwing an instance of 'std::runtime_error'
20:   what():  cudaMalloc( &ptr, arg_alloc_size ) error( cudaErrorMemoryAllocation): out of memory /users/chrism5/pumipic_Cabm/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:175
20: Traceback functionality not available
20: 
20: terminate called after throwing an instance of 'std::runtime_error'
20:   what():  cudaMalloc( &ptr, arg_alloc_size ) error( cudaErrorMemoryAllocation): out of memory /users/chrism5/pumipic_Cabm/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:175
20: Traceback functionality not available
20: 
20: terminate called after throwing an instance of 'std::runtime_error'
20:   what():  cudaMalloc( &ptr, arg_alloc_size ) error( cudaErrorMemoryAllocation): out of memory /users/chrism5/pumipic_Cabm/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:175
20: Traceback functionality not available
20: 
20: terminate called after throwing an instance of 'std::runtime_error'
20:   what():  cudaMalloc( &ptr, arg_alloc_size ) error( cudaErrorMemoryAllocation): out of memory /users/chrism5/pumipic_Cabm/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:175
20: Traceback functionality not available
```

Error on `test_structures_4`:

```
21: testMigration csr, rank 0
21: terminate called after throwing an instance of 'std::runtime_error'
21:   what():  cudaMalloc( &ptr, arg_alloc_size ) error( cudaErrorMemoryAllocation): out of memory /users/chrism5/pumipic_Cabm/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:175
21: Traceback functionality not available
21: 
21: terminate called after throwing an instance of 'std::runtime_error'
21:   what():  cudaMalloc( &ptr, arg_alloc_size ) error( cudaErrorMemoryAllocation): out of memory /users/chrism5/pumipic_Cabm/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:175
21: Traceback functionality not available
```

Secondly, I also just noticed that if this section is commented out, ignoring that error, we seemingly have yet another issue where `CabM` does not have the expected number of particles in each rank in the tests `SendToOne` and `migrateToEmptyAndRefill`, [here](https://github.com/SCOREC/pumi-pic/blob/926188ae560b8554877a4287e7c1b5455aad8365/particle_structs/test/test_migrate.cpp#L94-L146) and [here](https://github.com/SCOREC/pumi-pic/blob/926188ae560b8554877a4287e7c1b5455aad8365/particle_structs/test/test_migrate.cpp#L149-L254).

Error on `test_structures_small_4`:

```
20: testMigration cabm, rank 2
20: cabm Rank 1 has incorrect number of particles (24 != 23)
20: testSegmentComp cabm, rank 1
20: migrateToEmptyAndRefill cabm, rank 1
20: cabm Rank 3 has incorrect number of particles (26 != 25)
20: cabm Rank 0 has incorrect number of particles (26 != 26)
20: cabm Rank 2 has incorrect number of particles (24 != 23)
```

Error on `test_structures_4`:

```
21: testMigration cabm, rank 0
21: cabm Rank 3 has incorrect number of particles (9900 != 9899)
...
21: migrateToEmptyAndRefill cabm, rank 3
21: migrateToEmptyAndRefill cabm, rank 2
21: migrateToEmptyAndRefill cabm, rank 1
21: cabm Rank 0 has incorrect number of particles (10300 != 10301)
```

Both of these issues only occur during true migration by which I mean with multiple processes (otherwise migration doesn't happen and `migrate` just calls `rebuild`). I haven't found the source of these errors/bugs yet. They could be in the tests themselves.

**Comment by MatthewChristoff** [comment]
@cwsmith Uh, can you undo what I just did? I don't know how, but I pulled on my version of the csrMigrate branch and somehow it did something...I didn't want to happen? 

[this](https://github.com/SCOREC/pumi-pic/pull/63/commits/aa8ba772ec14f4f14040844fe2d075e0abbf9460)

**Comment by cwsmith** [comment]
@MatthewChristoff We can attempt to revert or rebase but likely there is no problem.  

It sounds like I made a mistake resolving the merge conflicts for the test.  If so, would you please commit a fix?

**Comment by MatthewChristoff** [comment]
@cwsmith Yeah...it looks fine. Sorry, I was just worried I broke something somehow. I made the change to remove `rebuild_csr.cpp`.

**Comment by MatthewChristoff** [comment]
@cwsmith The bug is fixed. We have one last issue that I'm not sure how to fix yet though. There's quite a few warnings on some `test_structures` tests about Kokkos mirror views being deallocated after a `Kokkos::finalize()` call. I'm not sure why this would be.

```
23: Kokkos allocation "subview_mirror" is being deallocated after Kokkos::finalize was called
23: This behavior is incorrect Kokkos usage, and will crash in future releases
```

**Comment by cwsmith** [comment]
Could it be from these calls where we use a subview to get a single value from a view on the device to the host:

https://github.com/SCOREC/pumi-pic/blob/52c28ba3353af8f2d499a19e31e163a24aed3cac/support/SupportKK.h#L138-L176

**Comment by diamog** [comment]
I believe those warnings are due to a PS nonblocking communication (PS_Isend, PS_Irecv, etc.) not having a corresponding wait/waitall. The nonblocking routines maintain a subview mirror until the wait is called

**Comment by MatthewChristoff** [comment]
@cwsmith @diamog Interesting. I've checked and the problem seems to be somewhere in `testMigration`, as expected. Looking into it.

**Comment by MatthewChristoff** [comment]
@cwsmith @diamog These warnings only come up with `test_structures_empty` and `test_structures_noptcls`, so this makes me think that there's some conditional for the appropriate wait call not being met when there are 0 particles being sent/received possibly.

**Comment by MatthewChristoff** [comment]
@cwsmith @diamog I found it. We had another conditional that defaulted to rebuild if no particles were being sent or received, but it was BEFORE the wait_all call for counting the number of send requests. I think we're all ready to merge now.

https://github.com/SCOREC/pumi-pic/pull/63/commits/f96c8eaff7f23903b78dccc56bc1f28a4578ef05

**Comment by cwsmith** [comment]
All tests with and without cabana enabled pass.

**Pull request merged**
