### PR TITLE
Kokkos 3 support

### PR DESCRIPTION
**Pull request by cwsmith**
This PR will support GITRm using reverse classification functionality from the SCOREC/omega_h master branch. SCOREC/omega_h is based on a newer version of SNL/omega_h that uses cmake files from Kokkos 3 which Kokkos 2 does not provide.

- [x] build and pass tests **without** cabana enabled on SCOREC workstation
- [x] build and pass tests **with** [cabana 0.3.0](https://github.com/ECP-copa/Cabana/releases/tag/0.3.0) enabled on SCOREC workstation
- [x] merge omegah/master into cws/kokkos3 and repeat above https://github.com/SCOREC/omega_h/commit/299508606076c049a4f9db6a32e8f526b91a3b21
- [x] merge cws/kokkos3 into omegah/master https://github.com/SCOREC/omega_h/commit/29545d273492f4aab6d125f8832bfb1cac3afc90
- [x] merge pumipic `fun3d` into pumipic master - pre-merge version tagged as [v0.3](https://github.com/SCOREC/pumi-pic/releases/tag/v0.3)
- [x] build gitrm `develop` branch
- [x] test gitrm  - 4200 steps of the ITER case executed on six aimos gpus without any obvious problems 
- [x] build and test xgcm
- [x] merge pumipic `master` into  pumipic `kokkos3100`
- [x] build and test xgcm - using [xgcm@kokkos3100](https://github.com/SCOREC/xgcm/tree/4afdda24df8d89b475b0e565df9fcfa45bd6cb97) 
- [x] install cmake 3.20 on aimos - `module load cmake` on aimos
- [x] build and test gitrm on aimos - using [gitrm@kokkos3100](https://github.com/SCOREC/gitrm/tree/kokkos3100)
- [ ] merge pumipic `kokkos3100` into  pumipic `master` - tag master before the merge - reference kokkos 2.9.00 in the tag
- [x] merge xgcm `kokkos3100` into xgcm `master` https://github.com/SCOREC/xgcm/pull/86
- [x] merge gitrm `kokkos3100` into gitrm `develop` https://github.com/SCOREC/gitrm/pull/44
- [ ] update build instructions
  - [x] omegah 
     - [x] [SCOREC](https://github.com/SCOREC/omega_h/wiki/Build-and-run-on-SCOREC-RHEL7-workstation)
     - [x] [AiMOS](https://github.com/SCOREC/omega_h/wiki/Build-and-run-on-AiMOS)
  - [ ] pumipic 
     - [ ] [SCOREC](https://github.com/SCOREC/pumi-pic/wiki/Building-and-Running-on-SCOREC-RHEL7) (updated in /space/cwsmith/ppScorecOmegahKk3/ppWiki)
     - [ ] [AiMOS](https://github.com/SCOREC/pumi-pic/wiki/Building-and-Running-on-AiMOS) (updated in /space/cwsmith/ppScorecOmegahKk3/ppWiki)
     - [ ] [Summit](https://github.com/SCOREC/pumi-pic/wiki/Building-and-Running-on-Summit)
  - [ ] gitrm - [AiMOS](https://github.com/SCOREC/gitrm/wiki/Build-on-AiMOS) (redirect to [here](https://github.com/SCOREC/gitrm/wiki/Build-and-run-on-AiMOS-using-Kokkos-3) once tested)
  - [ ] xgcm
    - [ ] [AiMOS](https://github.com/SCOREC/xgcm/wiki/Building-and-Running-on-AiMOS) (updated in /space/cwsmith/ppScorecOmegahKk3/xgcmWiki)
    - [ ] [SCOREC](https://github.com/SCOREC/xgcm/wiki/Building-and-Running-on-SCOREC-RHEL7) (updated in /space/cwsmith/ppScorecOmegahKk3/xgcmWiki)
    - [ ] delete this old and unused repo https://github.com/SCOREC/pumipicPetsc

### CODE REVIEW

**Comment by cwsmith** [comment]
pumipic, with and without cabana enabled, are passing all ctests using the `kokkos3100` branch.

**Comment by cwsmith** [comment]
omegah master merged into cws/kokkos3: https://github.com/SCOREC/omega_h/commit/299508606076c049a4f9db6a32e8f526b91a3b21, https://github.com/SCOREC/omega_h/commit/01623f4cae65d86add5c5b5b4f80b2556bcfb842 and cmake fixes pushed

The omegah ctest passes all tests except `warp_test_parallel`:

```
adapting took 4.06785 seconds                                                                                                                                                                                                                 
                                                                                                                                                                                                                                              
test took 34.2276 seconds                                                                                                                                                                                                                     
max diff at vertex 1008, comp 0, values 6.327799822371828e+01 vs 6.327799822371829e+01                                                                                                                                                        
vertex tag "metric" values are different                                                                                                                                                                                                      
edge tag "length" values are different                                                                                                                                                                                                        
max diff at edge 6073, comp 0, values 1.124971094950606e+00 vs 1.124971094950607e+00                                                                                                                                                          
tet tag "quality" values are different                                                                                                                                                                                                        
max diff at region 3483, comp 0, values 7.559526299369257e-01 vs 7.559526299369259e-01                                                                                                                                                        
This run, stored at "gold_warp_bad.osh",                                                                                                                                                                                                      
does not match the gold at "gold_warp.osh"                                                                                                                                                                                                    
<end of output>                                                                                                                                                                                                                               
Test time =  34.90 sec                                                                                                                                                                                                                        
----------------------------------------------------------                                                                                                                                                                                    
Test Failed.                                                                                                                                                                                                                                  
"warp_test_parallel" end time: Apr 21 16:08 EDT                                                                                                                                                                                               
"warp_test_parallel" time elapsed: 00:00:34                                                                                                                                                                                                   
----------------------------------------------------------   
```

This appears to be differences in the last digit and I assume can be ignored safely.

**Comment by cwsmith** [comment]
The pumipic 'master' branch has been merged into 'fun3dmesh' (working branch is here https://github.com/cwsmith/pumi-pic/commits/fun3dmesh) and is passing all but two of the ctests:

```
26 - barycentric_4 (Failed)
27 - linetri_intersection_2 (Failed)
```

The `fun3dmesh` branch prior to the merge also fails these tests (+two others).

The `gitrm` branch `update_develop` builds with the merged branch so I've merged `fun3dmesh` into pumipic `master`.  A test of the case in `/gpfs/u/home/MPFS/MPFSsmth/barn-shared/ITER_data` is queued.

**Comment by cwsmith** [comment]
XGCm is failing 16 of the 44 `ctest` tests on cranium with pumipic v0.3 (pre `fun3dmesh` merge) and with `master` (dcf019a).

@diamog @zhangchonglin I assume that most/all of these errors are known problems.  Is that correct?  If so, I'll proceed with testing using `kokkos3100` merged into `master`.

- 12 - test_scatter_1_8_1 (Failed) - assertion
```
sum(node_vol) = 3.84706
Building SCS with C: 32 sigma: 2147483647 V: 64
test_scatter: /space/cwsmith/ppCabm/xgcm/src/xgcm_grid.tpp:302: int xgcm::Grid<Device>::init_1d_psi_variables(xgcm::Mesh&, const xgcm::MagneticField<Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >&) [with Device = Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>]: Assertion `kindex >=0 && kindex < npsi_surf2' failed.
```

- 13 - test_scatter_4_4_1 (Failed) - out of memory
- 14 - test_scatter_1_4_2 (Failed) - assertion
```
sum(node_vol) = 3.84706
Building SCS with C: 32 sigma: 2147483647 V: 64
test_scatter: /space/cwsmith/ppCabm/xgcm/src/xgcm_grid.tpp:302: int xgcm::Grid<Device>::init_1d_psi_variables(xgcm::Mesh&, const xgcm::MagneticField<Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >&) [with Device = Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>]: Assertion `kindex >=0 && kindex < npsi_surf2' failed.
```
- 19 - test_2d_00_weight_d3d_1_4_1 (Failed) - assertion
```
sum(node_vol) = 3.84706
Building SCS with C: 32 sigma: 2147483647 V: 64
/space/cwsmith/ppCabm/xgcm/src/xgcm_grid.tpp:588: lambda [](int)->auto::operator()(int)->auto: block: [1,0,0], thread: [0,29,0] Assertion `major_f[ivert] >= epsilon && minor_f[ivert] >= epsilon` failed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorAssert): device-side assert triggered /space/cwsmith/ppCabm/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:120
Traceback functionality not available
```
- 20 - test_2d_00_weight_d3d_4_4_1 (Failed) - out of memory
- 24 - test_efield_1_8_1 (Failed) - assertion, same as test 14
- 25 - test_efield_shift_1_8_1 (Failed) - assertion, same as test 14
- 26 - test_efield_shift_1_4_2 (Failed) - assertion, same as test 14
- 27 - test_efield_shift_4_4_1 (Failed) - out of memory
- 28 - test_efield_scatter_1_8_1 (Failed) - assertion, same as test 14
- 29 - test_efield_print_1_8_1 (Failed) - assertion, same as test 14
- 36 - test_XGCm_petsc_37kElms_4m_1p_2g_field (Failed) - multiple ranks per group not supported
- 38 - test_XGCm_solver_Cyclone_37kElms_1m_4p_1g_field (Failed) - assertion
```
solution vector
L_2 norm of (A*u-b) / b: 8.52794e-07
set_tag(vertices, solution): tag doesn't exist (use add_tag first)
  Linear solve converged due to CONVERGED_RTOL iterations 4
KSP final norm of residual 1.07355e+07
solution vector
L_2 norm of (A*u-b) / b: 8.52794e-07
set_tag(vertices, solution): tag doesn't exist (use add_tag first)
solution vector
L_2 norm of (A*u-b) / b: 8.52794e-07
set_tag(vertices, solution): tag doesn't exist (use add_tag first)
solution vector
L_2 norm of (A*u-b) / b: 8.52794e-07
set_tag(vertices, solution): tag doesn't exist (use add_tag first)
```
- 39 - test_XGCm_solver_D3D_24kElms_1m_4p_1g_field (Failed) - assertion, same as test 19
- 42 - XGCm_24kElms_1m_8p_1g (Failed) - assertion, same as test 14
- 43 - XGCm_24kElms_1m_8p_1g_petsc (Failed) - assertion, same as test 14

**Comment by zhangchonglin** [comment]
Please proceed, these are issues mostly due to vertex mismatch and group member > 1: https://github.com/SCOREC/xgcm/issues/67#issuecomment-806316303.

**Comment by cwsmith** [comment]
@zhangchonglin OK.  Thank you for the quick response.

**Comment by dhyan1272** [comment]
I compared the results for 100k particles 100 k time steps. They are exactly the same (except difference in the 15th decimal place at 3 or 4 places)

________________________________

**Comment by cwsmith** [comment]
@dhyan1272 Thank you.  I deleted the `fun3dmesh` branch.

**Comment by cwsmith** [comment]
Xgcm @ kokkos3100 (one commit ahead of master 27f6ea), built against pumipic@kokkos3100, fails one more test than xgcm@master built against pumipic@v0.3:

```
Building SCS with C: 32 sigma: 2147483647 V: 1024                                                                                                                                                                                             
Building SCS with C: 1 sigma: 2147483647 V: 1024                                                                                                                                                                                              
max iterations: 1                                                                                                                                                                                                                             
total number of particles = 263752 263752 0                                                                                                                                                                                                   
total number of particles = 0.263752 0.263752 0 million                                                                                                                                                                                       
iteration 1 particles 263752; 0.263752 million                                                                                                                                                                                                
ranks with particles 8 particle imbalance 1.000000                                                                                                                                                                                            
Kokkos::abort: Requested Team Size is too large!Kokkos::abort: Requested Team Size is too large!Kokkos::abort: Requested Team Size is too large!Kokkos::abort: Requested Team Size is too large!Kokkos::abort: Requested Team Size is too large!Kokkos::abort: Requested Team Size is too large!Kokkos::abort: Requested Team Size is too large!Kokkos::abort: Requested Team Size is too large!         
```

The output prior to the failure is identical.  

No other xgcm or pumipic tests fail with the `Kokkos::abort: Requested Team Size is too large!` error.

**Comment by cwsmith** [comment]
It looks like the xgcm error is during a copy of the electron SCS (with zero particles) to the host during RK iterations:
https://github.com/SCOREC/xgcm/blob/4afdda24df8d89b475b0e565df9fcfa45bd6cb97/src/xgcm_rkloop.cpp#L29-L30

**Comment by cwsmith** [comment]
@dhyan1272 Would you please try building gitrm following the instructions here:

https://github.com/SCOREC/gitrm/wiki/Build-and-run-on-AiMOS-using-Kokkos-3

and running the `~/barn-shared/ITER_data` test case.  My build executed 6236 steps on four 16GB GPUs without any obvious issues.

**Comment by dhyan1272** [comment]
Is this the latest version of GITRm (develop branch)?
________________________________

**Comment by cwsmith** [comment]
@dhyan1272 There is a branch of gitrm (based on `develop`) that the instructions use.

**Comment by cwsmith** [comment]
GITRm results using Kokkos 3.1 were verified.  https://github.com/SCOREC/gitrm/issues/43#issuecomment-847835006

These branches are ready to be merged.

**Pull request merged**
